version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: anime_api
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: 12341234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

